version: 1.4.{build}
image: Visual Studio 2013
environment:
  matrix:
    - MSVC: msvc2013
      VCVARSPARAM: x86
      DBG:
    - MSVC: msvc2013_64
      VCVARSPARAM: x64
      DBG:
    - MSVC: msvc2013
      VCVARSPARAM: x86
      DBG: CONFIG+=debug
    - MSVC: msvc2013_64
      VCVARSPARAM: x64
      DBG: CONFIG+=debug
build_script:
- cmd: "echo building for arch: %VCVARSPARAM% msvc: %MSVC%"
- cmd: set PATH=C:\Qt\5.6\%MSVC%\bin;%PATH%
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %VCVARSPARAM%
- cmd: qmake %DBG% quickaccess.pro
- cmd: dir
- cmd: nmake
- cmd: dir
artifacts:
- path: release/*.dp32
  name: release_x86
- path: release/*.dp64
  name: release_x64
- path: debug/*.dp32
  name: debug_x32
- path: debug/*.dp64
  name: debug_x64
deploy:
- provider: GitHub
  on:
    branch: master
  artifact: release_x86,release_x64
  auth_token:
    secure: pVX8UX9OlbhF5BSC8Qv7HG3BkuiOp7IRHSYJf7NMqc/hNRRKi/tHTaVMmcXM2M3g
