name: 'sched_check_load_plugin'
on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Every time
        run: bash ${GITHUB_WORKSPACE}/.devcontainer/sched_check_load_plugin.sh