name: 'sched_check_load_plugin'
on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: ls -lah ${GITHUB_WORKSPACE} && ls -lah ${GITHUB_WORKSPACE}/.devcontainer bash ${GITHUB_WORKSPACE}/.devcontainer/sched_check_load_plugin.sh
